# repoctl configuration

# repo is the full path to the repository that will be managed by repoctl.
# The packages that belong to the repository are assumed to lie in the
# same folder.
repo = "/srv/http/chaotic-aur/x86_64/chaotic-aur.db.tar.gz"

# add_params is the set of parameters that will be passed to repo-add
# when it is called. Specify one time for each parameter.
#add_params = []

# rm_params is the set of parameters that will be passed to repo-remove
# when it is called. Specify one time for each parameter.
#rm_params = []

# ignore_aur is a set of package names that are ignored in conjunction
# with AUR related tasks, such as determining if there is an update or not.
ignore_aur = ["clang-analyzer-git","clang-analyzer-svn","clang-compiler-rt-git","clang-compiler-rt-svn",
"clang-git","clang-minimal-git","clang-svn","clang-tools-extra-git","clang-tools-extra-svn","compiler-rt-minimal-git",
"coreaction-git","corearchiver-git","corefm-git","coregarage-git","corehunt-git",
"coreimage-git","coreinfo-git","corepad-git","corepaint-git","corepdf-git",
"corepins-git","coreplayer-git","corerenamer-git","coreshot-git","corekeyboard-git",
"corestats-git","corestuff-git","coreterminal-git","coretime-git","coreuniverse-git",
"dxvk-git","dxvk-wine32-git","dxvk-wine64-git","ffmpeg-full","firefox-hg","firefox-wayland-hg","kplasmafoxhelper","lib32-clang-git",
"lib32-clang-svn","lib32-llvm-git","lib32-llvm-libs-git","lib32-llvm-libs-minimal-git","lib32-llvm-libs-svn","lib32-llvm-minimal-git",
"lib32-llvm-svn","lib32-mesa-tkg-git","lib32-nvidia-dev-utils-tkg","lib32-nvidia-utils-tkg","lib32-opencl-nvidia-dev-tkg",
"lib32-opencl-nvidia-tkg","libarchive-qt-git","libcprime-git","libcsys-git",
"linux-lts-tkg-bmq","linux-lts-tkg-bmq-headers","linux-lts-tkg-muqss","linux-lts-tkg-muqss-headers","linux-lts-tkg-pds",
"linux-lts-tkg-pds-headers","linux-tkg-bmq-atom","linux-tkg-bmq-barcelona","linux-tkg-bmq-bobcat","linux-tkg-bmq-broadwell",
"linux-tkg-bmq-bulldozer","linux-tkg-bmq-cannonlake","linux-tkg-bmq-core2","linux-tkg-bmq-excavator","linux-tkg-bmq-haswell",
"linux-tkg-bmq-icelake","linux-tkg-bmq-ivybridge","linux-tkg-bmq-jaguar","linux-tkg-bmq-k10","linux-tkg-bmq-k8","linux-tkg-bmq-k8sse3",
"linux-tkg-bmq-mpsc","linux-tkg-bmq-nehalem","linux-tkg-bmq-piledriver","linux-tkg-bmq-sandybridge","linux-tkg-bmq-silvermont",
"linux-tkg-bmq-skylake","linux-tkg-bmq-skylakex","linux-tkg-bmq-steamroller","linux-tkg-bmq-westmere","linux-tkg-bmq-zen",
"linux-tkg-bmq-zen2","linux-tkg-muqss-atom","linux-tkg-muqss-barcelona","linux-tkg-muqss-bobcat","linux-tkg-muqss-broadwell",
"linux-tkg-muqss-bulldozer","linux-tkg-muqss-cannonlake","linux-tkg-muqss-core2","linux-tkg-muqss-excavator","linux-tkg-muqss-haswell",
"linux-tkg-muqss-icelake","linux-tkg-muqss-ivybridge","linux-tkg-muqss-jaguar","linux-tkg-muqss-k10","linux-tkg-muqss-k8",
"linux-tkg-muqss-k8sse3","linux-tkg-muqss-mpsc","linux-tkg-muqss-nehalem","linux-tkg-muqss-piledriver","linux-tkg-muqss-sandybridge",
"linux-tkg-muqss-silvermont","linux-tkg-muqss-skylake","linux-tkg-muqss-skylakex","linux-tkg-muqss-steamroller","linux-tkg-muqss-westmere",
"linux-tkg-muqss-zen","linux-tkg-muqss-zen2","linux-tkg-pds-atom","linux-tkg-pds-barcelona","linux-tkg-pds-bobcat","linux-tkg-pds-broadwell",
"linux-tkg-pds-bulldozer","linux-tkg-pds-cannonlake","linux-tkg-pds-core2","linux-tkg-pds-excavator","linux-tkg-pds-haswell",
"linux-tkg-pds-icelake","linux-tkg-pds-ivybridge","linux-tkg-pds-jaguar","linux-tkg-pds-k10","linux-tkg-pds-k8","linux-tkg-pds-k8sse3",
"linux-tkg-pds-mpsc","linux-tkg-pds-nehalem","linux-tkg-pds-piledriver","linux-tkg-pds-sandybridge","linux-tkg-pds-silvermont",
"linux-tkg-pds-skylake","linux-tkg-pds-skylakex","linux-tkg-pds-steamroller","linux-tkg-pds-westmere","linux-tkg-pds-zen",
"linux-tkg-pds-zen2","lldb-git","lldb-svn","lld-git","lld-svn","llvm-git","llvm-libs-git","llvm-libs-minimal-git","llvm-libs-svn",
"llvm-minimal-git","llvm-ocaml-git","llvm-ocaml-svn","llvm-svn","lone_wolf-clang-git","lone_wolf-compiler-rt-git","lone_wolf-lib32-llvm-git",
"lone_wolf-lib32-llvm-libs-git","lone_wolf-llvm-git","lone_wolf-llvm-libs-git","lone_wolf-ocaml-git","manjarowish-dark-kde-settings",
"manjarowish-light-kde-settings","manjarowish-lxqt-kwin-dark-settings","manjarowish-lxqt-kwin-light-settings","manjarowish-pantheon-settings",
"mesa-tkg-git","mir-git","nss-hg","nvidia-dev-dkms-tkg","nvidia-dev-egl-wayland-tkg","nvidia-dev-utils-tkg","nvidia-dkms-tkg",
"nvidia-egl-wayland-tkg","nvidia-tkg","nvidia-utils-tkg","ocaml-minimal-git","opencl-nvidia-dev-tkg","opencl-nvidia-tkg","plasmafox",
"retdec-git","rpcs3-git","vlc-git","vulkan-headers-git","wine-tkg-fsync-faudio-git","wine-tkg-fsync-faudio-opt-git","wine-tkg-fsync-git",
"wine-tkg-fsync-opt-git","wine-tkg-fsync-vkd3d-faudio-git","wine-tkg-fsync-vkd3d-faudio-opt-git","wine-tkg-fsync-vkd3d-git",
"wine-tkg-fsync-vkd3d-opt-git","wine-tkg-staging-fsync-faudio-git","wine-tkg-staging-fsync-faudio-opt-git","wine-tkg-staging-fsync-git",
"wine-tkg-staging-fsync-opt-git","wine-tkg-staging-fsync-vkd3d-faudio-git","wine-tkg-staging-fsync-vkd3d-faudio-opt-git",
"wine-tkg-staging-fsync-vkd3d-git","wine-tkg-staging-fsync-vkd3d-opt-git","wireguard-dkms-git","wireguard-tools-git","xamarin-android-git",
"xamarin-android-proprietary-git"]

# backup specifies whether package files should be backed up or deleted.
# If it is set to false, then obsolete package files are deleted.
backup = true

# backup_dir specifies which directory backups are stored in.
# - If a relative path is given, then it is interpreted as relative to
#   the repository directory.
# - If the path here resolves to the same as repo, then obsolete packages
#   are effectively ignored by repoctl, if backup is true.
backup_dir = "/srv/http/chaotic-aur/archive/"

# interactive specifies that repoctl should ask before doing anything
# destructive.
interactive = false

# columnate specifies that listings should be in columns rather than
# in lines. This only applies to the list command.
columnate = false

# color specifies when to use color. Can be one of auto, always, and never.
color = "auto"

# quiet specifies whether repoctl should print more information or less.
# I prefer to know what happens, but if you don't like it, you can change it.
quiet = false

# pre_action is a command that should be executed before doing anything
# with the repository, like reading or modifying it. Useful for mounting
# a remote filesystem.
#pre_action = ""

# post_action is a command that should be executed before exiting.
#post_action = ""

# action_on_completion determines whether repols should perform the
# actions or not. By default, this is disallowed.
#action_on_completion = false
